-- Schema Postgres (Supabase). Espelho do schema.sql do SQLite.
--
-- As duas versões precisam descrever a MESMA tabela: os mesmos totais têm que sair
-- do banco de teste e do banco de produção, senão a suíte deixa de provar qualquer
-- coisa sobre o que roda de verdade. As diferenças abaixo são de dialeto, nunca de
-- modelo — quando uma coluna mudar aqui, ela muda lá também.
--
-- CARGA INCREMENTAL
-- A identidade de uma linha é o par (hash_linha, ocorrencia):
--
--   hash_linha -> sha1 dos 6 campos do fato (om, oficina, data, mp, qtd, minutos)
--   ocorrencia -> 1, 2, 3... para linhas idênticas DENTRO do mesmo arquivo
--
-- O índice ÚNICO sobre esse par é o que faz re-subir a mesma planilha não inserir
-- nada, preservando as cópias legítimas que a origem declara. É o mecanismo
-- inteiro da carga incremental; sem ele o histórico duplica a cada upload.

-- Sem os DROPs de tabelas legadas que existem no schema.sql: aquelas tabelas
-- (ordens, recebimentos, oficinas...) só existiram em bancos SQLite antigos e
-- nunca chegaram a ser criadas aqui.

-- Três decisões de tipo que valem explicação:
--
-- DOUBLE PRECISION, e não REAL. O REAL do Postgres é float de 4 bytes (~6 dígitos
-- significativos), enquanto o REAL do SQLite é de 8. Usar REAL aqui arredondaria
-- silenciosamente as somas de peças e minutos, quebrando o invariante central do
-- projeto: o total da tela tem que bater com a soma da coluna no Excel.
--
-- TEXT para data/deadline, e não DATE. O hash da linha é calculado em Python sobre
-- a data em ISO; manter o tipo idêntico ao do SQLite garante que a mesma planilha
-- gere o mesmo hash nos dois bancos. Migrar para DATE é possível depois, isolado,
-- com o hash já estável.
--
-- GENERATED BY DEFAULT, e não ALWAYS. O script de migração grava os ids originais
-- vindos do SQLite para preservar o histórico de cargas; ALWAYS proibiria isso.

CREATE TABLE IF NOT EXISTS fato_acompanhamento (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina    TEXT             NOT NULL,
    data       TEXT,                              -- ISO 'YYYY-MM-DD' (coluna ENVIO)
    mp         TEXT             NOT NULL,
    qtd_pecas  DOUBLE PRECISION NOT NULL DEFAULT 0,
    minutos    DOUBLE PRECISION NOT NULL DEFAULT 0,
    om         BIGINT,                            -- ORDEM MESTRE
    -- Prazo de entrega. A origem exporta parte das linhas com o ano anterior; o
    -- ETL reescreve o ano antes de gravar (ver etl.corrigir_ano_deadline).
    deadline   TEXT,                              -- ISO 'YYYY-MM-DD' (coluna DEAD LINE)
    hash_linha TEXT             NOT NULL,
    ocorrencia INTEGER          NOT NULL DEFAULT 1,
    carga_id   BIGINT
);

CREATE TABLE IF NOT EXISTS fato_recebimento (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina    TEXT             NOT NULL,
    data       TEXT,                              -- ISO 'YYYY-MM-DD' (coluna DIA)
    mp         TEXT             NOT NULL,
    qtd_pecas  DOUBLE PRECISION NOT NULL DEFAULT 0,   -- REAL CORTADO
    minutos    DOUBLE PRECISION NOT NULL DEFAULT 0,
    om         BIGINT,
    hash_linha TEXT             NOT NULL,
    ocorrencia INTEGER          NOT NULL DEFAULT 1,
    carga_id   BIGINT
);

CREATE TABLE IF NOT EXISTS fato_envios (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina    TEXT             NOT NULL,
    data       TEXT,                              -- ISO 'YYYY-MM-DD' (coluna ENVIO)
    mp         TEXT             NOT NULL,
    qtd_pecas  DOUBLE PRECISION NOT NULL DEFAULT 0,
    minutos    DOUBLE PRECISION NOT NULL DEFAULT 0,
    om         BIGINT,
    hash_linha TEXT             NOT NULL,
    ocorrencia INTEGER          NOT NULL DEFAULT 1,
    carga_id   BIGINT
);

-- Previsão: a agenda do que ainda vai voltar das oficinas. Como o Acompanhamento,
-- é um retrato do momento (a ordem some da planilha quando volta), e por isso a
-- tabela é substituída por inteiro a cada carga.
--
-- Aqui `data` é a data PREVISTA de recebimento, e não o envio: é ela que responde
-- "o que temos para receber nesta semana", que é a pergunta da tela. O envio ganha
-- coluna própria justamente porque perdeu o lugar de `data`.
CREATE TABLE IF NOT EXISTS fato_previsao (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oficina    TEXT             NOT NULL,
    data       TEXT,                              -- ISO 'YYYY-MM-DD' (coluna RECEBIMENTO)
    mp         TEXT             NOT NULL,
    qtd_pecas  DOUBLE PRECISION NOT NULL DEFAULT 0,
    minutos    DOUBLE PRECISION NOT NULL DEFAULT 0,
    om         BIGINT,                            -- ORDEM MESTRE
    deadline   TEXT,                              -- ISO 'YYYY-MM-DD' (coluna DEAD LINE)
    envio      TEXT,                              -- ISO 'YYYY-MM-DD' (coluna ENVIO)
    hash_linha TEXT             NOT NULL,
    ocorrencia INTEGER          NOT NULL DEFAULT 1,
    carga_id   BIGINT
);

CREATE INDEX IF NOT EXISTS ix_acomp_data  ON fato_acompanhamento (data);
CREATE INDEX IF NOT EXISTS ix_receb_data  ON fato_recebimento (data);
CREATE INDEX IF NOT EXISTS ix_envios_data ON fato_envios (data);
CREATE INDEX IF NOT EXISTS ix_prev_data   ON fato_previsao (data);

-- O alvo do ON CONFLICT usado por dialeto.DialetoPostgres.sql_insert. Aqui as duas
-- colunas são NOT NULL, então o par identifica a linha sem exceção — no SQLite,
-- onde bancos antigos podem ter hash nulo, a garantia é mais fraca.
CREATE UNIQUE INDEX IF NOT EXISTS ux_acomp_linha  ON fato_acompanhamento (hash_linha, ocorrencia);
CREATE UNIQUE INDEX IF NOT EXISTS ux_receb_linha  ON fato_recebimento (hash_linha, ocorrencia);
CREATE UNIQUE INDEX IF NOT EXISTS ux_envios_linha ON fato_envios (hash_linha, ocorrencia);
CREATE UNIQUE INDEX IF NOT EXISTS ux_prev_linha   ON fato_previsao (hash_linha, ocorrencia);

-- Metas: chave/valor, cadastradas pelo time. Recarregar planilhas não as toca.
CREATE TABLE IF NOT EXISTS metas (
    chave         TEXT PRIMARY KEY,
    valor         DOUBLE PRECISION NOT NULL DEFAULT 0,
    atualizado_em TEXT
);

-- Log de cargas: o que entrou, quando e de qual arquivo. É o que permite auditar
-- uma carga suspeita e responder "por que este número mudou ontem?".
CREATE TABLE IF NOT EXISTS cargas (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fonte            TEXT NOT NULL,
    arquivo          TEXT,
    quando           TEXT NOT NULL,
    modo             TEXT NOT NULL,     -- 'incremental' ou 'substituicao'
    linhas_lidas     INTEGER NOT NULL DEFAULT 0,
    linhas_novas     INTEGER NOT NULL DEFAULT 0,
    linhas_repetidas INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_cargas_quando ON cargas (quando);
